import numpy as np
x = np.arange(0, 10, 0.01)
y = np.sin(x)
z = np.cos(x)
p = np.cosh(x)
q = np.sinh(x)
print('sine values of x from 0 to 10 with increment 0.01')
print(y)
print('cosine values of x from 0 to 10 with increment 0.01')
print(z)
print ('hyperbolic cosine functions')
print(p)
print('hyperbolic sine functions')
print(q)
